CREATE OR REPLACE VIEW V_User_Cms AS SELECT `id`, `version`, `isDeleted`, `authProvider`, `providerIdentity`, `avatarId`, `coverId` FROM User;
CREATE TRIGGER IF NOT EXISTS User_TU_SetavatarIdNullWhenEmpty BEFORE UPDATE ON User FOR EACH ROW SET NEW.`avatarId` = NULLIF(NEW.`avatarId`, '');
CREATE TRIGGER IF NOT EXISTS User_TI_SetavatarIdNullWhenEmpty BEFORE INSERT ON User FOR EACH ROW SET NEW.`avatarId` = NULLIF(NEW.`avatarId`, '');
CREATE TRIGGER IF NOT EXISTS User_TU_SetcoverIdNullWhenEmpty BEFORE UPDATE ON User FOR EACH ROW SET NEW.`coverId` = NULLIF(NEW.`coverId`, '');
CREATE TRIGGER IF NOT EXISTS User_TI_SetcoverIdNullWhenEmpty BEFORE INSERT ON User FOR EACH ROW SET NEW.`coverId` = NULLIF(NEW.`coverId`, '');
CREATE TABLE `acsys_V_User_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_UserEmail_Cms AS SELECT `id`, `version`, `isDeleted`, `userId`, `isVerified`, `orderNum`, `email` FROM UserEmail;
CREATE TABLE `acsys_V_UserEmail_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_Image_Cms AS SELECT `id`, `version`, `isDeleted`, `slug`, `categoryId`, `ownerId`, `fileId`, `invertForDarkTheme`, `stubCssStyle` FROM Image;
CREATE TRIGGER IF NOT EXISTS Image_TU_SetownerIdNullWhenEmpty BEFORE UPDATE ON Image FOR EACH ROW SET NEW.`ownerId` = NULLIF(NEW.`ownerId`, '');
CREATE TRIGGER IF NOT EXISTS Image_TI_SetownerIdNullWhenEmpty BEFORE INSERT ON Image FOR EACH ROW SET NEW.`ownerId` = NULLIF(NEW.`ownerId`, '');
CREATE TRIGGER IF NOT EXISTS Image_TU_SetstubCssStyleNullWhenEmpty BEFORE UPDATE ON Image FOR EACH ROW SET NEW.`stubCssStyle` = NULLIF(NEW.`stubCssStyle`, '');
CREATE TRIGGER IF NOT EXISTS Image_TI_SetstubCssStyleNullWhenEmpty BEFORE INSERT ON Image FOR EACH ROW SET NEW.`stubCssStyle` = NULLIF(NEW.`stubCssStyle`, '');
CREATE OR REPLACE VIEW acsys_V_Image_Cms AS SELECT `id`, `version`, `isDeleted`, `slug`, `categoryId`, `ownerId`, `fileId`, `invertForDarkTheme`, `stubCssStyle` FROM AcsysDraftsImage;
CREATE TRIGGER IF NOT EXISTS AcsysDraftsImage_TU_SetownerIdNullWhenEmpty BEFORE UPDATE ON AcsysDraftsImage FOR EACH ROW SET NEW.`ownerId` = NULLIF(NEW.`ownerId`, '');
CREATE TRIGGER IF NOT EXISTS AcsysDraftsImage_TI_SetownerIdNullWhenEmpty BEFORE INSERT ON AcsysDraftsImage FOR EACH ROW SET NEW.`ownerId` = NULLIF(NEW.`ownerId`, '');
CREATE TRIGGER IF NOT EXISTS AcsysDraftsImage_TU_SetstubCssStyleNullWhenEmpty BEFORE UPDATE ON AcsysDraftsImage FOR EACH ROW SET NEW.`stubCssStyle` = NULLIF(NEW.`stubCssStyle`, '');
CREATE TRIGGER IF NOT EXISTS AcsysDraftsImage_TI_SetstubCssStyleNullWhenEmpty BEFORE INSERT ON AcsysDraftsImage FOR EACH ROW SET NEW.`stubCssStyle` = NULLIF(NEW.`stubCssStyle`, '');
CREATE OR REPLACE VIEW V_ImageCategory_Cms AS SELECT `id`, `version`, `kind`, `width`, `height` FROM ImageCategory;
CREATE TABLE `acsys_V_ImageCategory_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_AuthFormImage_Cms AS SELECT `id`, `version`, `isDeleted`, `imageId`, `orderNum` FROM AuthFormImage;
CREATE OR REPLACE VIEW acsys_V_AuthFormImage_Cms AS SELECT `id`, `version`, `isDeleted`, `imageId`, `orderNum` FROM AcsysDraftsAuthFormImage;
CREATE OR REPLACE VIEW V_Flight_Cms AS SELECT `id`, `version`, `isDeleted`, `airlineCompanyId`, `airplaneId`, `departmentAirportId`, `arrivalAirportId`, `departmentUtcPosix`, `arrivalUtcPosix` FROM Flight;
CREATE TABLE `acsys_V_Flight_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_FlightOffer_Cms AS SELECT `id`, `version`, `isDeleted`, `departFlightId`, `returnFlightId`, `totalPrice`, `numPassengers`, `class` FROM FlightOffer;
CREATE TRIGGER IF NOT EXISTS FlightOffer_TU_SetreturnFlightIdNullWhenEmpty BEFORE UPDATE ON FlightOffer FOR EACH ROW SET NEW.`returnFlightId` = NULLIF(NEW.`returnFlightId`, '');
CREATE TRIGGER IF NOT EXISTS FlightOffer_TI_SetreturnFlightIdNullWhenEmpty BEFORE INSERT ON FlightOffer FOR EACH ROW SET NEW.`returnFlightId` = NULLIF(NEW.`returnFlightId`, '');
CREATE TABLE `acsys_V_FlightOffer_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_StayOffer_Cms AS SELECT `id`, `version`, `isDeleted`, `hotelId`, `totalPrice`, `checkInPosix`, `checkOutPosix`, `numRooms`, `numGuests` FROM StayOffer;
CREATE TABLE `acsys_V_StayOffer_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_UserFlightOffer_Cms AS SELECT `id`, `version`, `isDeleted`, `offerId`, `userId`, `isFavourite` FROM UserFlightOffer;
CREATE TABLE `acsys_V_UserFlightOffer_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_Hotel_Cms AS SELECT `id`, `version`, `isDeleted`, `cityId`, `nameStrId`, `slug`, `lon`, `lat` FROM Hotel;
CREATE OR REPLACE VIEW acsys_V_Hotel_Cms AS SELECT `id`, `version`, `isDeleted`, `cityId`, `nameStrId`, `slug`, `lon`, `lat` FROM AcsysDraftsHotel;
CREATE OR REPLACE VIEW V_HotelDescription_Cms AS SELECT `id`, `version`, `isDeleted`, `hotelId`, `textStrId`, `paragraphKind`, `orderNum` FROM HotelDescription;
CREATE OR REPLACE VIEW acsys_V_HotelDescription_Cms AS SELECT `id`, `version`, `isDeleted`, `hotelId`, `textStrId`, `paragraphKind`, `orderNum` FROM AcsysDraftsHotelDescription;
CREATE OR REPLACE VIEW V_HotelReview_Cms AS SELECT `id`, `version`, `isDeleted`, `hotelId`, `userId`, `textStrId`, `score` FROM HotelReview;
CREATE OR REPLACE VIEW acsys_V_HotelReview_Cms AS SELECT `id`, `version`, `isDeleted`, `hotelId`, `userId`, `textStrId`, `score` FROM AcsysDraftsHotelReview;
CREATE OR REPLACE VIEW V_HotelImage_Cms AS SELECT `id`, `version`, `isDeleted`, `hotelId`, `imageId`, `serviceLevel`, `orderNum` FROM HotelImage;
CREATE TRIGGER IF NOT EXISTS HotelImage_TU_SetserviceLevelNullWhenEmpty BEFORE UPDATE ON HotelImage FOR EACH ROW SET NEW.`serviceLevel` = NULLIF(NEW.`serviceLevel`, '');
CREATE TRIGGER IF NOT EXISTS HotelImage_TI_SetserviceLevelNullWhenEmpty BEFORE INSERT ON HotelImage FOR EACH ROW SET NEW.`serviceLevel` = NULLIF(NEW.`serviceLevel`, '');
CREATE OR REPLACE VIEW acsys_V_HotelImage_Cms AS SELECT `id`, `version`, `isDeleted`, `hotelId`, `imageId`, `serviceLevel`, `orderNum` FROM AcsysDraftsHotelImage;
CREATE TRIGGER IF NOT EXISTS AcsysDraftsHotelImage_TU_SetserviceLevelNullWhenEmpty BEFORE UPDATE ON AcsysDraftsHotelImage FOR EACH ROW SET NEW.`serviceLevel` = NULLIF(NEW.`serviceLevel`, '');
CREATE TRIGGER IF NOT EXISTS AcsysDraftsHotelImage_TI_SetserviceLevelNullWhenEmpty BEFORE INSERT ON AcsysDraftsHotelImage FOR EACH ROW SET NEW.`serviceLevel` = NULLIF(NEW.`serviceLevel`, '');
CREATE OR REPLACE VIEW V_Booking_Cms AS SELECT `id`, `version`, `isDeleted`, `flightOfferId`, `stayOfferId`, `userId`, `serviceLevel` FROM Booking;
CREATE TRIGGER IF NOT EXISTS Booking_TU_SetflightOfferIdNullWhenEmpty BEFORE UPDATE ON Booking FOR EACH ROW SET NEW.`flightOfferId` = NULLIF(NEW.`flightOfferId`, '');
CREATE TRIGGER IF NOT EXISTS Booking_TI_SetflightOfferIdNullWhenEmpty BEFORE INSERT ON Booking FOR EACH ROW SET NEW.`flightOfferId` = NULLIF(NEW.`flightOfferId`, '');
CREATE TRIGGER IF NOT EXISTS Booking_TU_SetstayOfferIdNullWhenEmpty BEFORE UPDATE ON Booking FOR EACH ROW SET NEW.`stayOfferId` = NULLIF(NEW.`stayOfferId`, '');
CREATE TRIGGER IF NOT EXISTS Booking_TI_SetstayOfferIdNullWhenEmpty BEFORE INSERT ON Booking FOR EACH ROW SET NEW.`stayOfferId` = NULLIF(NEW.`stayOfferId`, '');
CREATE TRIGGER IF NOT EXISTS Booking_TU_SetserviceLevelNullWhenEmpty BEFORE UPDATE ON Booking FOR EACH ROW SET NEW.`serviceLevel` = NULLIF(NEW.`serviceLevel`, '');
CREATE TRIGGER IF NOT EXISTS Booking_TI_SetserviceLevelNullWhenEmpty BEFORE INSERT ON Booking FOR EACH ROW SET NEW.`serviceLevel` = NULLIF(NEW.`serviceLevel`, '');
CREATE TABLE `acsys_V_Booking_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_PopularCity_Cms AS SELECT `id`, `version`, `cityId`, `promoLineStrId`, `travelHeaderStrId`, `travelTextStrId`, `rating`, `visibleOnWorldMap` FROM PopularCity;
CREATE TABLE `acsys_V_PopularCity_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_PopularCityImage_Cms AS SELECT `id`, `version`, `isDeleted`, `popularCityId`, `imageId`, `orderNum` FROM PopularCityImage;
CREATE OR REPLACE VIEW acsys_V_PopularCityImage_Cms AS SELECT `id`, `version`, `isDeleted`, `popularCityId`, `imageId`, `orderNum` FROM AcsysDraftsPopularCityImage;
CREATE OR REPLACE VIEW V_Country_Cms AS SELECT `id`, `version`, `isDeleted`, `nameStrId` FROM Country;
CREATE TABLE `acsys_V_Country_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_City_Cms AS SELECT `id`, `version`, `isDeleted`, `nameStrId`, `countryId`, `slug`, `textForSearch`, `lon`, `lat`, `population`, `utcOffsetMin` FROM City;
CREATE OR REPLACE VIEW acsys_V_City_Cms AS SELECT `id`, `version`, `isDeleted`, `nameStrId`, `countryId`, `slug`, `textForSearch`, `lon`, `lat`, `population`, `utcOffsetMin` FROM AcsysDraftsCity;
CREATE OR REPLACE VIEW V_Airport_Cms AS SELECT `id`, `version`, `isDeleted`, `cityId`, `nameStrId`, `lon`, `lat` FROM Airport;
CREATE OR REPLACE VIEW acsys_V_Airport_Cms AS SELECT `id`, `version`, `isDeleted`, `cityId`, `nameStrId`, `lon`, `lat` FROM AcsysDraftsAirport;
CREATE OR REPLACE VIEW V_CompanyReview_Cms AS SELECT `id`, `version`, `isDeleted`, `personNameStrId`, `imageId`, `headerStrId`, `bodyStrId` FROM CompanyReview;
CREATE OR REPLACE VIEW acsys_V_CompanyReview_Cms AS SELECT `id`, `version`, `isDeleted`, `personNameStrId`, `imageId`, `headerStrId`, `bodyStrId` FROM AcsysDraftsCompanyReview;
CREATE OR REPLACE VIEW V_AirlineCompany_Cms AS SELECT `id`, `version`, `isDeleted`, `nameStrId`, `cityId`, `logoImageId`, `numReviews`, `reviewScore` FROM AirlineCompany;
CREATE OR REPLACE VIEW acsys_V_AirlineCompany_Cms AS SELECT `id`, `version`, `isDeleted`, `nameStrId`, `cityId`, `logoImageId`, `numReviews`, `reviewScore` FROM AcsysDraftsAirlineCompany;
CREATE OR REPLACE VIEW V_Airplane_Cms AS SELECT `id`, `version`, `isDeleted`, `nameStrId` FROM Airplane;
CREATE OR REPLACE VIEW acsys_V_Airplane_Cms AS SELECT `id`, `version`, `isDeleted`, `nameStrId` FROM AcsysDraftsAirplane;
CREATE OR REPLACE VIEW V_AirplaneImage_Cms AS SELECT `id`, `version`, `isDeleted`, `airplaneId`, `kind`, `orderNum`, `imageId` FROM AirplaneImage;
CREATE OR REPLACE VIEW acsys_V_AirplaneImage_Cms AS SELECT `id`, `version`, `isDeleted`, `airplaneId`, `kind`, `orderNum`, `imageId` FROM AcsysDraftsAirplaneImage;
CREATE OR REPLACE VIEW V_MailTemplate_Cms AS SELECT `id`, `version`, `isDeleted`, `templateStrId`, `kind` FROM MailTemplate;
CREATE OR REPLACE VIEW acsys_V_MailTemplate_Cms AS SELECT `id`, `version`, `isDeleted`, `templateStrId`, `kind` FROM AcsysDraftsMailTemplate;
CREATE OR REPLACE VIEW V_VerificationToken_Cms AS SELECT `id`, `version`, `isDeleted`, `userId`, `kind`, `attemptsMade` FROM VerificationToken;
CREATE TABLE `acsys_V_VerificationToken_Cms` ( `dummy` INT NOT NULL ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE OR REPLACE VIEW V_LocalizeableValue_Cms AS SELECT `id`, `version`, `isDeleted`, `en`, `ru`, `fr` FROM LocalizeableValue;
CREATE OR REPLACE VIEW acsys_V_LocalizeableValue_Cms AS SELECT `id`, `version`, `isDeleted`, `en`, `ru`, `fr` FROM AcsysDraftsLocalizeableValue;
